name: interview_target_sistemas
description: A new Flutter project.

publish_to: "Gabeloper"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  http: ^1.1.0
  mobx: ^2.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.4
  faker: ^2.1.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  mocktail: ^1.0.1

  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/
